### ISSUE TITLE
fs.watch fails when watching a huge amount of images

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/sync-s3#1]
`sync-s3` crashes when watching a huge amount of images, this happens when the Raspberry Pi is restarted. `fs.watch` should only watch new files, and should not load all existing files on startup.

**Comment by cedricve** [comment]
On Linux, `inotify` is used. Inotify limits the number of watched files, this setting can be found in `/proc/sys/fs/inotify/max_user_watches`. Some users have found problems with the cloud syncing process; images weren't synced to the cloud application anymore after a reboot.

This problem only occurs with users, who've expanded the partition of the SD card. This is the reason why the number of images could exceed the inotify limit, and why users who didn't expanded the SD card didn't had this problem.

To resolve this problem you should increase the limit to a larger/very large number.

`echo 999999999 > /proc/sys/fs/inotify/max_user_watches`

![screen shot 2015-08-02 at 13 44 32](https://cloud.githubusercontent.com/assets/1546779/9025989/847fe236-391d-11e5-8006-e3ea6334bf46.png)

**Comment by cedricve** [comment]
@kr15 you should do this to make the changes permanent:

      nano /usr/lib/sysctl.d/50-default.conf
      
      # add following line at the end of the file
      fs.inotify.max_user_watches=99999999999999999

**Comment by kr15h** [comment]
Ok, just did it, rebooting. Will let you know if it works.

**Comment by kr15h** [comment]
Ok, it works now. I had to:

1. Exec this: `echo 999999999 > /proc/sys/fs/inotify/max_user_watches`
2. Add `fs.inotify.max_user_watches=99999999999999999` to `/usr/lib/sysctl.d/50-default.conf`
3. Delete everything from `/home/kerberos-web/public/capture` and `/home/could/symbols`
4. Reboot
5. Move in front of the camera to trigger activity

Now I have 2 cams, let's see how it goes for the following week!

**Comment by kr15h** [comment]
Yeah—it's so much more fun with 2 cameras : ]

**Comment by kr15h** [comment]
Hi. The issue is still there. The disk is full and the script is not syncing anymore.

**Comment by kr15h** [comment]
Sorry - it works. There was a DNS problem.
