### ISSUE TITLE
Not uploading when disk is full

### ISSUE THREAD

**Issue by kr15h** [kerberos-io/sync-s3#2]
I am using a 8GB SD card and created a cloud.kerberos.io test account. I noticed that the latest activities are not synced with the Kerberos Cloud anymore, probably because the disk is full.

**Comment by cedricve** [comment]
Please check this issue, it will be fixed in next release.
https://github.com/kerberos-io/sync-s3/issues/1

**Comment by kr15h** [comment]
oh, cool, thanks @cedricve !

**Comment by kr15h** [comment]
@cedricve should I reboot after `echo 999999999 > /proc/sys/fs/inotify/max_user_watches` ?

**Comment by cedricve** [comment]
@kr15h please issue https://github.com/kerberos-io/sync-s3/issues/1
