### ISSUE TITLE
Is only the current activity synced?

### ISSUE THREAD

**Issue by kr15h** [kerberos-io/sync-s3#3]
Here is my scenario: The network stopped working 3 days ago and obviously 3 days of activities were not synced to the cloud. What happens when network is working again? The new activities are synced - what happens with the old ones?

**Comment by cedricve** [comment]
When uploading fails, nothing will happen, as the reference for syncing the specific image is not removed. Please see following link; https://github.com/kerberos-io/sync-s3/blob/master/Gruntfile.js#L199-L206.

I would expect if you reboot the Raspberry Pi, or update the configuration page of Kerberos, the sync-s3 proces will sync the images which weren't synced so far. Can you please try this?

Are there any symbol links in `/home/cloud/symbols`, if yes than the above procedure will upload them to the cloud application.

**Comment by kr15h** [comment]
Thanks. I tried to update the settings page (changed the camera name) as well as restart the pi. No new images from previous days appear on the cloud. I noticed another problem now. One of the cameras can not be accessed anymore via the browser: 502 Bad Gateway error. I can still access it through ssh. Have you experienced this?

**Comment by kr15h** [comment]
There are no symbols in the directory.

**Comment by cedricve** [comment]
What happens when rebooting?

**Comment by kr15h** [comment]
Not much. At some points it might be the DNS settings that are messing things up, but not all the time.

**Comment by cedricve** [comment]
Hmm, but you still can access the Raspberry Pi by ssh? You did expand the SD card right, can youn clean up the image directory and look if the issue is resolved.

**Comment by cedricve** [comment]
About the symbols directory, this means the script crashed. We will take a look at the source why thos could happen. Are you sure the network stopped working, or you think it does because the syncing stopped?

**Comment by kr15h** [comment]
I reset (by burning the sd card again) the alarmpi that had the 502 error. For now there is something terribly wrong with dns on our network, but I did expand the sd card of the pi that does not upload the previous images and does not have symbols. I will continue debugging, but I don't have too much experience with Arch Linux and Nginx. It's getting better, but not so fast. Maybe you have a brief kerberos-web architecture overview laying around somewhere or you could write it? Just where to start, what loads what, how things are started up on system start - things like that?

**Comment by cedricve** [comment]
Hmm, don't think this will have anything to do with your DNS. As you are using the cloud, I wouldn't expand the SD card, instead if you will be using the Kerberos image for other goals or a custom setup.
The web interface is built with the PHP framework Laravel, you'll find all the information on their website; it's really straight forward, and it has a very nice documentation website.

**Comment by kr15h** [comment]
Ok, thanks. I expanded the partition because that's what you usually do after installing Raspbian.

**Comment by cedricve** [comment]
You can always join our gitter channel, if you want to start a discussion.
